services:
  app:
    image: clouddock-cicd
    container_name: clouddock_app
    expose:
      - "5000"
    environment:
      - ENV=production

  nginx:
    image: nginx:latest
    container_name: clouddock_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
