services:
  app:
    image: unifyapps-devops
    container_name: unifyapps_app
    expose:
      - "5000"
    environment:
      - ENV=production

  nginx:
    image: nginx:latest
    container_name: unifyapps_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
